create table if not exists public.developer_access (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  expires_at timestamptz,
  revoked_at timestamptz,
  is_protected boolean not null default false
);

create table if not exists public.filament_brands (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_families (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.material_subtypes (
  id bigint generated by default as identity primary key,
  family_id bigint not null references public.material_families(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(family_id, name)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_filament_brands_updated_at on public.filament_brands;
create trigger set_filament_brands_updated_at
before update on public.filament_brands
for each row execute function public.set_updated_at();

drop trigger if exists set_material_families_updated_at on public.material_families;
create trigger set_material_families_updated_at
before update on public.material_families
for each row execute function public.set_updated_at();

drop trigger if exists set_material_subtypes_updated_at on public.material_subtypes;
create trigger set_material_subtypes_updated_at
before update on public.material_subtypes
for each row execute function public.set_updated_at();

create or replace function public.normalize_developer_access()
returns trigger
language plpgsql
as $$
begin
  new.email = lower(trim(new.email));

  if new.email = 'vishrutsn@gmail.com' then
    new.is_protected = true;
    new.expires_at = null;
    new.revoked_at = null;
  end if;

  if tg_op = 'UPDATE' and old.email = 'vishrutsn@gmail.com' then
    if new.email <> old.email or new.is_protected is not true or new.expires_at is not null or new.revoked_at is not null then
      raise exception 'The primary developer cannot be changed, expired, or revoked.';
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.prevent_primary_developer_delete()
returns trigger
language plpgsql
as $$
begin
  if old.email = 'vishrutsn@gmail.com' then
    raise exception 'The primary developer cannot be deleted.';
  end if;
  return old;
end;
$$;

drop trigger if exists normalize_developer_access on public.developer_access;
create trigger normalize_developer_access
before insert or update on public.developer_access
for each row execute function public.normalize_developer_access();

drop trigger if exists prevent_primary_developer_delete on public.developer_access;
create trigger prevent_primary_developer_delete
before delete on public.developer_access
for each row execute function public.prevent_primary_developer_delete();

insert into public.developer_access (email, is_protected, expires_at, revoked_at)
values ('vishrutsn@gmail.com', true, null, null)
on conflict (email) do update
set is_protected = true,
    expires_at = null,
    revoked_at = null;

insert into public.filament_brands (name) values
('3D Solutech'),
('3D Warhorse'),
('3D-Fuel'),
('3DHoJor'),
('3DQF'),
('3DXTech'),
('Amazon Basics'),
('Amolen'),
('Anycubic'),
('Atomic Filament'),
('Bambu Lab'),
('BASF Forward AM'),
('CC3D'),
('ColorFabb'),
('Creality'),
('Das Filament'),
('Deeplee'),
('DSM'),
('Duramic'),
('Elegoo'),
('Eryone'),
('eSun'),
('Extrudr'),
('Fiberlogy'),
('Fiberon'),
('Filamentive'),
('Fillamentum'),
('Flashforge'),
('FLSUN'),
('FormFutura'),
('Geeetech'),
('Giantarm'),
('Gizmo Dorks'),
('Hatchbox'),
('IC3D'),
('IEMAI'),
('Inland'),
('iSANMATE'),
('Jayo'),
('Kimya'),
('Kingroon'),
('MatterHackers'),
('NinjaTek'),
('Noctuo'),
('NovaMaker'),
('Other'),
('Overture'),
('PolyLite'),
('Polymaker'),
('PolySonic'),
('PolyTerra'),
('Proto-Pasta'),
('Prusa'),
('Prusament'),
('Raise3D'),
('Redline'),
('Rigid.ink'),
('Smartfil'),
('Spectrum Filaments'),
('Sunlu'),
('Taulman3D'),
('Tecbears'),
('TTYT3D'),
('Ultimaker'),
('Velleman'),
('Ziro'),
('Zortrax')
on conflict (name) do nothing;

insert into public.material_families (name) values
('PLA'), ('PETG'), ('ABS'), ('ASA'), ('TPU'), ('PC'), ('PA'), ('PET'), ('PVA'),
('HIPS'), ('PEEK'), ('PEKK'), ('PEI'), ('Nylon'), ('Resin'), ('Support'), ('Composite'), ('Other')
on conflict (name) do nothing;

insert into public.material_subtypes (family_id, name)
select mf.id, seed.name
from public.material_families mf
join (values
('PLA', 'Standard'), ('PLA', 'PLA+'), ('PLA', 'Tough'), ('PLA', 'Matte'), ('PLA', 'Silk'), ('PLA', 'Silk Rainbow'), ('PLA', 'Carbon Fiber'), ('PLA', 'Glass Fiber'), ('PLA', 'Wood Fill'), ('PLA', 'Metal Fill'), ('PLA', 'Marble'), ('PLA', 'Glow in the Dark'), ('PLA', 'Conductive'), ('PLA', 'ESD'), ('PLA', 'HF'), ('PLA', 'HS'), ('PLA', 'High Temp'), ('PLA', 'Transparent'), ('PLA', 'Translucent'), ('PLA', 'Recycled'), ('PLA', 'Lightweight'),
('PETG', 'Standard'), ('PETG', 'PETG+'), ('PETG', 'Matte'), ('PETG', 'Carbon Fiber'), ('PETG', 'Glass Fiber'), ('PETG', 'Conductive'), ('PETG', 'ESD'), ('PETG', 'HF'), ('PETG', 'HS'), ('PETG', 'Transparent'), ('PETG', 'Translucent'), ('PETG', 'Recycled'),
('ABS', 'Standard'), ('ABS', 'ABS+'), ('ABS', 'Carbon Fiber'), ('ABS', 'Glass Fiber'), ('ABS', 'ESD'), ('ABS', 'Conductive'), ('ABS', 'Flame Retardant'), ('ABS', 'HF'), ('ABS', 'HS'), ('ABS', 'High Temp'),
('ASA', 'Standard'), ('ASA', 'UV Resistant'), ('ASA', 'Aero'), ('ASA', 'Carbon Fiber'), ('ASA', 'Glass Fiber'), ('ASA', 'ESD'), ('ASA', 'HF'), ('ASA', 'HS'),
('TPU', '95A'), ('TPU', '90A'), ('TPU', '85A'), ('TPU', '75A'), ('TPU', '60D'), ('TPU', 'Flexible'), ('TPU', 'HF'), ('TPU', 'HS'), ('TPU', 'Conductive'), ('TPU', 'ESD'), ('TPU', 'Carbon Fiber'),
('PC', 'Standard'), ('PC', 'PC-ABS'), ('PC', 'PC-PBT'), ('PC', 'Carbon Fiber'), ('PC', 'Glass Fiber'), ('PC', 'Transparent'), ('PC', 'HF'), ('PC', 'HS'), ('PC', 'High Temp'), ('PC', 'Flame Retardant'),
('PA', 'PA6'), ('PA', 'PA12'), ('PA', 'PA-CF'), ('PA', 'PA-GF'), ('PA', 'PAHT'), ('PA', 'PA6-CF'), ('PA', 'PA12-CF'), ('PA', 'PA6-GF'), ('PA', 'Flexible'), ('PA', 'ESD'), ('PA', 'HF'), ('PA', 'HS'), ('PA', 'High Temp'),
('PET', 'Standard'), ('PET', 'Recycled'), ('PET', 'Transparent'), ('PET', 'Translucent'), ('PET', 'HF'), ('PET', 'HS'), ('PET', 'High Temp'),
('PVA', 'Standard'), ('PVA', 'Fast-Dissolve'), ('PVA', 'Soluble Support'), ('PVA', 'Interface Support'), ('PVA', 'HF'), ('PVA', 'HS'),
('HIPS', 'Standard'), ('HIPS', 'Support'), ('HIPS', 'High Impact'), ('HIPS', 'Soluble Support'),
('PEEK', 'Standard'), ('PEEK', 'Carbon Fiber'), ('PEEK', 'Glass Fiber'), ('PEEK', 'ESD'), ('PEEK', 'High Temp'),
('PEKK', 'Standard'), ('PEKK', 'Carbon Fiber'), ('PEKK', 'High Temp'),
('PEI', 'Standard'), ('PEI', 'ULTEM 9085'), ('PEI', 'ULTEM 1010'), ('PEI', 'Carbon Fiber'), ('PEI', 'High Temp'),
('Nylon', 'Nylon 6'), ('Nylon', 'Nylon 12'), ('Nylon', 'Carbon Fiber'), ('Nylon', 'Glass Fiber'), ('Nylon', 'Flexible'), ('Nylon', 'ESD'), ('Nylon', 'HF'), ('Nylon', 'HS'), ('Nylon', 'High Temp'),
('Resin', 'Standard'), ('Resin', 'ABS-Like'), ('Resin', 'Flexible'), ('Resin', 'Tough'), ('Resin', 'Dental'), ('Resin', 'Engineering'), ('Resin', 'High Temp'), ('Resin', 'Castable'), ('Resin', 'Transparent'),
('Support', 'PVA'), ('Support', 'BVOH'), ('Support', 'HIPS'), ('Support', 'Breakaway'), ('Support', 'Soluble'), ('Support', 'Interface'), ('Support', 'Support W'), ('Support', 'Support G'),
('Composite', 'Carbon Fiber'), ('Composite', 'Glass Fiber'), ('Composite', 'Wood Fill'), ('Composite', 'Metal Fill'), ('Composite', 'Glow'), ('Composite', 'Conductive'), ('Composite', 'ESD'), ('Composite', 'Ceramic Fill'),
('Other', 'Custom'), ('Other', 'Composite'), ('Other', 'Support'), ('Other', 'Soluble'), ('Other', 'Conductive'), ('Other', 'ESD'), ('Other', 'Glow'), ('Other', 'Metal Fill'), ('Other', 'Wood Fill'), ('Other', 'Carbon Fiber'), ('Other', 'Glass Fiber'), ('Other', 'High Speed'), ('Other', 'High Temp'), ('Other', 'Recycled'), ('Other', 'Transparent'), ('Other', 'Flexible')
) as seed(family, name) on mf.name = seed.family
on conflict (family_id, name) do nothing;

create or replace function public.is_developer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.developer_access da
    where lower(da.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and da.revoked_at is null
      and (da.expires_at is null or da.expires_at > now())
  );
$$;

alter table public.developer_access enable row level security;
alter table public.filament_brands enable row level security;
alter table public.material_families enable row level security;
alter table public.material_subtypes enable row level security;

drop policy if exists "Developers can select dev access" on public.developer_access;
drop policy if exists "Developers can insert dev access" on public.developer_access;
drop policy if exists "Developers can update dev access" on public.developer_access;
drop policy if exists "Developers can delete dev access" on public.developer_access;
drop policy if exists "Users can select their own dev access" on public.developer_access;

create policy "Developers can select dev access"
on public.developer_access for select to authenticated
using (public.is_developer());

create policy "Users can select their own dev access"
on public.developer_access for select to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

create policy "Developers can insert dev access"
on public.developer_access for insert to authenticated
with check (public.is_developer());

create policy "Developers can update dev access"
on public.developer_access for update to authenticated
using (public.is_developer())
with check (public.is_developer());

create policy "Developers can delete dev access"
on public.developer_access for delete to authenticated
using (public.is_developer());

drop policy if exists "Anyone can read filament brands" on public.filament_brands;
drop policy if exists "Developers can insert filament brands" on public.filament_brands;
drop policy if exists "Developers can update filament brands" on public.filament_brands;
drop policy if exists "Developers can delete filament brands" on public.filament_brands;

create policy "Anyone can read filament brands"
on public.filament_brands for select to anon, authenticated
using (true);

create policy "Developers can insert filament brands"
on public.filament_brands for insert to authenticated
with check (public.is_developer());

create policy "Developers can update filament brands"
on public.filament_brands for update to authenticated
using (public.is_developer())
with check (public.is_developer());

create policy "Developers can delete filament brands"
on public.filament_brands for delete to authenticated
using (public.is_developer());

drop policy if exists "Anyone can read material families" on public.material_families;
drop policy if exists "Developers can insert material families" on public.material_families;
drop policy if exists "Developers can update material families" on public.material_families;
drop policy if exists "Developers can delete material families" on public.material_families;

create policy "Anyone can read material families"
on public.material_families for select to anon, authenticated
using (true);

create policy "Developers can insert material families"
on public.material_families for insert to authenticated
with check (public.is_developer());

create policy "Developers can update material families"
on public.material_families for update to authenticated
using (public.is_developer())
with check (public.is_developer());

create policy "Developers can delete material families"
on public.material_families for delete to authenticated
using (public.is_developer());

drop policy if exists "Anyone can read material subtypes" on public.material_subtypes;
drop policy if exists "Developers can insert material subtypes" on public.material_subtypes;
drop policy if exists "Developers can update material subtypes" on public.material_subtypes;
drop policy if exists "Developers can delete material subtypes" on public.material_subtypes;

create policy "Anyone can read material subtypes"
on public.material_subtypes for select to anon, authenticated
using (true);

create policy "Developers can insert material subtypes"
on public.material_subtypes for insert to authenticated
with check (public.is_developer());

create policy "Developers can update material subtypes"
on public.material_subtypes for update to authenticated
using (public.is_developer())
with check (public.is_developer());

create policy "Developers can delete material subtypes"
on public.material_subtypes for delete to authenticated
using (public.is_developer());

grant select on public.filament_brands to anon, authenticated;
grant select on public.material_families to anon, authenticated;
grant select on public.material_subtypes to anon, authenticated;
grant insert, update, delete on public.filament_brands to authenticated;
grant insert, update, delete on public.material_families to authenticated;
grant insert, update, delete on public.material_subtypes to authenticated;
grant select, insert, update, delete on public.developer_access to authenticated;
grant usage, select on sequence public.developer_access_id_seq to authenticated;
grant usage, select on sequence public.filament_brands_id_seq to authenticated;
grant usage, select on sequence public.material_families_id_seq to authenticated;
grant usage, select on sequence public.material_subtypes_id_seq to authenticated;
