create table if not exists public.filaments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,

  brand text not null,
  product_line text,
  material_family text not null,
  material_subtype text,
  color_name text,
  color_hex text not null default '#888888',

  advertised_weight numeric(8, 2),
  spool_type text,
  spool_material text,
  measurement_method text not null default 'empty_spool'
    check (measurement_method in ('empty_spool', 'full_spool')),
  empty_spool_weight numeric(8, 2),
  full_spool_weight numeric(8, 2),
  current_total_weight numeric(8, 2),
  remaining_grams numeric(8, 2),
  remaining_percent numeric(5, 2),

  purchase_link text,
  supplier text,
  price numeric(10, 2),
  date_purchased timestamptz,
  storage_location text,
  is_dry_box boolean not null default false,
  last_dried_at timestamptz,

  notes text,
  custom_labels text,
  max_volumetric_flow numeric(8, 3),
  pressure_advance numeric(8, 4),
  nozzle_temp_min integer,
  nozzle_temp_max integer,
  bed_temp integer,
  chamber_temp integer,
  cooling_fan_percent integer,
  recommended_speed integer,
  drying_temp integer,
  drying_time text,
  slicer_notes text,
  is_archived boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists filaments_user_id_idx
  on public.filaments(user_id);

create index if not exists filaments_user_updated_at_idx
  on public.filaments(user_id, updated_at desc);

alter table public.filaments add column if not exists max_volumetric_flow numeric(8, 3);
alter table public.filaments add column if not exists pressure_advance numeric(8, 4);
alter table public.filaments add column if not exists nozzle_temp_min integer;
alter table public.filaments add column if not exists nozzle_temp_max integer;
alter table public.filaments add column if not exists bed_temp integer;
alter table public.filaments add column if not exists chamber_temp integer;
alter table public.filaments add column if not exists cooling_fan_percent integer;
alter table public.filaments add column if not exists recommended_speed integer;
alter table public.filaments add column if not exists drying_temp integer;
alter table public.filaments add column if not exists drying_time text;
alter table public.filaments add column if not exists slicer_notes text;

grant select, insert, update, delete on public.filaments to authenticated;
grant usage, select on sequence public.filaments_id_seq to authenticated;

create or replace function public.set_filaments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_filaments_updated_at on public.filaments;

create trigger set_filaments_updated_at
before update on public.filaments
for each row
execute function public.set_filaments_updated_at();

alter table public.filaments enable row level security;

drop policy if exists "Users can select their own filaments" on public.filaments;
drop policy if exists "Users can insert their own filaments" on public.filaments;
drop policy if exists "Users can update their own filaments" on public.filaments;
drop policy if exists "Users can delete their own filaments" on public.filaments;

create policy "Users can select their own filaments"
on public.filaments
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own filaments"
on public.filaments
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own filaments"
on public.filaments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own filaments"
on public.filaments
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.print_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  print_name text not null,
  description text,
  filament_id bigint references public.filaments(id) on delete set null,
  filament_label text,
  grams_used numeric(10, 2) not null,
  filament_before_grams numeric(10, 2),
  filament_after_grams numeric(10, 2),
  mode text not null default 'one_time' check (mode in ('one_time', 'new', 'reprint')),
  printed_at timestamptz not null default now()
);

alter table public.print_logs add column if not exists filament_before_grams numeric(10, 2);
alter table public.print_logs add column if not exists filament_after_grams numeric(10, 2);

create table if not exists public.quick_print_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  estimated_grams numeric(10, 2) not null,
  estimated_cost numeric(10, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

grant select, insert, update, delete on public.print_logs to authenticated;
grant select, insert, update, delete on public.quick_print_templates to authenticated;
grant usage, select on sequence public.print_logs_id_seq to authenticated;
grant usage, select on sequence public.quick_print_templates_id_seq to authenticated;

alter table public.print_logs enable row level security;
alter table public.quick_print_templates enable row level security;

drop policy if exists "Users can select their own print logs" on public.print_logs;
drop policy if exists "Users can insert their own print logs" on public.print_logs;
drop policy if exists "Users can update their own print logs" on public.print_logs;
drop policy if exists "Users can delete their own print logs" on public.print_logs;

create policy "Users can select their own print logs" on public.print_logs
for select to authenticated using (auth.uid() = user_id);
create policy "Users can insert their own print logs" on public.print_logs
for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can update their own print logs" on public.print_logs
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own print logs" on public.print_logs
for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can select their own quick print templates" on public.quick_print_templates;
drop policy if exists "Users can insert their own quick print templates" on public.quick_print_templates;
drop policy if exists "Users can update their own quick print templates" on public.quick_print_templates;
drop policy if exists "Users can delete their own quick print templates" on public.quick_print_templates;

create policy "Users can select their own quick print templates" on public.quick_print_templates
for select to authenticated using (auth.uid() = user_id);
create policy "Users can insert their own quick print templates" on public.quick_print_templates
for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can update their own quick print templates" on public.quick_print_templates
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can delete their own quick print templates" on public.quick_print_templates
for delete to authenticated using (auth.uid() = user_id);
