create table if not exists public.filaments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,

  brand text not null,
  product_line text,
  material_family text not null,
  material_subtype text,
  color_name text,
  color_hex text not null default '#888888',

  advertised_weight numeric(8, 2),
  spool_type text,
  spool_material text,
  measurement_method text not null default 'empty_spool'
    check (measurement_method in ('empty_spool', 'full_spool')),
  empty_spool_weight numeric(8, 2),
  full_spool_weight numeric(8, 2),
  current_total_weight numeric(8, 2),
  remaining_grams numeric(8, 2),
  remaining_percent numeric(5, 2),

  purchase_link text,
  supplier text,
  price numeric(10, 2),
  date_purchased timestamptz,
  storage_location text,
  is_dry_box boolean not null default false,
  last_dried_at timestamptz,

  notes text,
  custom_labels text,
  is_archived boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists filaments_user_id_idx
  on public.filaments(user_id);

create index if not exists filaments_user_updated_at_idx
  on public.filaments(user_id, updated_at desc);

grant select, insert, update, delete on public.filaments to authenticated;
grant usage, select on sequence public.filaments_id_seq to authenticated;

create or replace function public.set_filaments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_filaments_updated_at on public.filaments;

create trigger set_filaments_updated_at
before update on public.filaments
for each row
execute function public.set_filaments_updated_at();

alter table public.filaments enable row level security;

drop policy if exists "Users can select their own filaments" on public.filaments;
drop policy if exists "Users can insert their own filaments" on public.filaments;
drop policy if exists "Users can update their own filaments" on public.filaments;
drop policy if exists "Users can delete their own filaments" on public.filaments;

create policy "Users can select their own filaments"
on public.filaments
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own filaments"
on public.filaments
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own filaments"
on public.filaments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own filaments"
on public.filaments
for delete
to authenticated
using (auth.uid() = user_id);
