CREATE TABLE `filaments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`brand` varchar(128) NOT NULL,
	`productLine` varchar(128),
	`materialFamily` varchar(64) NOT NULL,
	`materialSubtype` varchar(64),
	`colorName` varchar(128),
	`colorHex` varchar(7) NOT NULL DEFAULT '#888888',
	`advertisedWeight` decimal(8,2),
	`spoolType` varchar(64),
	`spoolMaterial` varchar(64),
	`measurementMethod` enum('empty_spool','full_spool') DEFAULT 'empty_spool',
	`emptySpoolWeight` decimal(8,2),
	`fullSpoolWeight` decimal(8,2),
	`currentTotalWeight` decimal(8,2),
	`remainingGrams` decimal(8,2),
	`remainingPercent` decimal(5,2),
	`purchaseLink` text,
	`supplier` varchar(128),
	`price` decimal(10,2),
	`datePurchased` timestamp,
	`storageLocation` varchar(128),
	`isDryBox` boolean DEFAULT false,
	`lastDriedAt` timestamp,
	`notes` text,
	`customLabels` text,
	`isArchived` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `filaments_id` PRIMARY KEY(`id`)
);
